# Generated by Django 4.2.30 on 2026-04-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging')], max_length=20)),
                ('status', models.CharField(choices=[('live', 'Live'), ('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('template_id', models.CharField(blank=True, max_length=100)),
                ('agent_external_id', models.CharField(blank=True, max_length=100)),
                ('schema', models.CharField(blank=True, max_length=100)),
                ('lang', models.CharField(default='en-IN', max_length=50)),
                ('stt_engine', models.CharField(default='Deepgram', max_length=50)),
                ('tts_engine', models.CharField(default='ElevenLabs', max_length=50)),
                ('llm_model', models.CharField(default='gemini-flash-2.0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calling_window_start', models.TimeField(blank=True, null=True)),
                ('calling_window_end', models.TimeField(blank=True, null=True)),
                ('backup_attempts', models.PositiveSmallIntegerField(default=3)),
                ('message_start_time', models.TimeField(blank=True, null=True)),
                ('message_stop_time', models.TimeField(blank=True, null=True)),
                ('follow_up_duration', models.PositiveSmallIntegerField(default=24)),
                ('filler_audio', models.BooleanField(default=False)),
                ('detect_voice_mail', models.BooleanField(default=True)),
                ('barge_in', models.BooleanField(default=True)),
                ('open_socket_tts', models.BooleanField(default=False)),
                ('utterance_end', models.BooleanField(default=False)),
                ('deepgram_model', models.CharField(default='nova-2', max_length=50)),
                ('utterance_end_ms', models.PositiveIntegerField(default=1000)),
                ('endpointing_ms', models.PositiveIntegerField(default=300)),
                ('auto_punctuation', models.BooleanField(default=True)),
                ('filler_audio_path', models.TextField(blank=True)),
                ('voice', models.CharField(default='Maria', max_length=100)),
                ('speed', models.FloatField(default=1.0)),
                ('stability', models.FloatField(default=0.5)),
                ('similarity', models.FloatField(default=0.75)),
                ('nlu_uuid', models.CharField(blank=True, max_length=200)),
                ('nlu_env_id', models.CharField(blank=True, max_length=200)),
                ('startup_text', models.TextField(blank=True)),
                ('notification_emails', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='agents.agent')),
            ],
        ),
    ]
